# Generated by Django 4.0.3 on 2022-06-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='close_time',
        ),
    ]
