# Generated by Django 4.0.3 on 2022-06-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='app/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='app/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='app/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='app/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='app/images/')),
                ('shortinfo', models.TextField(default='NA')),
                ('description', models.TextField(default='NA')),
                ('weight', models.FloatField(default=0.0)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('fav_count', models.IntegerField(blank=True, null=True)),
                ('latest', models.DateField()),
                ('category', models.CharField(choices=[('FL', 'Farine_Semoul'), ('P', 'Pates'), ('G', 'Gateaux'), ('S', 'Sucrerie'), ('OF', 'Graines'), ('L', 'Laitiers'), ('B', 'Boisson'), ('PFM', 'Produit_Fait_Maison'), ('E', 'Epices'), ('CM', 'Compliment Alimentaire'), ('PGP', 'Produit_Gateaux_Patisserie')], max_length=3)),
                ('quantity1', models.CharField(choices=[('sold', 'sold'), ('available', 'available')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=17)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
