# Generated by Django 4.0.3 on 2022-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categ_product_kharya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kharya',
            new_name='categ',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity1',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=10),
        ),
    ]
