# Generated by Django 4.0.3 on 2022-06-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_kharya_product_categ_alter_product_quantity1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categ',
        ),
        migrations.DeleteModel(
            name='Categ',
        ),
    ]
