# Generated by Django 4.0.3 on 2022-06-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_categ_delete_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity1',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available')], default='available', max_length=10),
        ),
    ]
