# Generated by Django 4.0.3 on 2022-06-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_customer_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='order_num',
        ),
    ]
