# Generated by Django 4.0.3 on 2022-06-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_order_shippingaddress_order_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order_num',
            new_name='order',
        ),
    ]
