# Generated by Django 4.0.3 on 2022-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_order_num_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity1',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=10),
        ),
    ]
