# Generated by Django 4.0.3 on 2022-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_quantity1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
