# Generated by Django 4.0.3 on 2022-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orderitem_quantity_alter_product_quantity1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity1',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
