# Generated by Django 4.0.3 on 2022-06-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_category_alter_product_quantity1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity1',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=10),
        ),
    ]
